name: Generate contribution snake (SVG)

on:
  schedule:
    # roda 1 vez por dia (vocÃª pode ajustar)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate github contribution grid snake (SVG only)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: CarvalhoMatheuss
          theme: dark
          output: output/github-contribution-grid-snake-dark.svg

      - name: Commit generated SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p output
          git add output/github-contribution-grid-snake-dark.svg
          git commit -m "chore: update contribution snake" || echo "no changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
